version: '3'
services:
  react-frontend:
    build: .
    volumes:
     - type: bind
       source: ./src
       target: /app/src
    environment:
      - NODE_ENV=VITE_dev
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - node-backend
  node-backend:
    image: "kamsci/garden-aid-api:latest"
    user: "node"
    environment:
      - NODE_ENV=dev
    env_file:
      - backend.env
    ports:
      - "3000:3000"
